# Generated by Django 2.1 on 2018-08-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('konten', models.TextField()),
                ('status', models.CharField(choices=[('PUBLISH', 'Publish'), ('DRAFT', 'Draft'), ('DELETE', 'Delete')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Topik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judulTopik', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='topik',
            field=models.ManyToManyField(to='crudapi.Topik'),
        ),
    ]
