# Generated by Django 2.1 on 2018-08-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('PUBLISH', 'Publish'), ('DRAFT', 'Draft'), ('DELETE', 'Delete')], default='DRAFT', max_length=20),
        ),
    ]
